# ✅ Archivo corregido para despliegue en Netlify
# @fileoverview Configuración de build y deploy para Boost Agency (Angular)
# @author 
# Boost Agency Development Team

[build]
  base = "frontend"
  publish = "dist/frontend"  # ← CORREGIDO: sin /browser
  command = "npm install && npx ng build --configuration production"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# (Opcional) Configuración para desarrollo local con Netlify CLI
[dev]
  command = "ng serve"
  port = 4200
  publish = "dist/frontend"  # ← CORREGIDO aquí también
 
