# ✅ Archivo correctamente documentado
# @fileoverview Configuración de despliegue en Netlify para Boost Agency
# 
# Este archivo define la configuración de build y despliegue
# para la aplicación Angular en la plataforma Netlify.
# 
# @author Boost Agency Development Team
# @version 1.0.0

[build]
  base = "frontend"                                    # Directorio base del proyecto
  publish = "dist/frontend/browser"                    # Directorio de archivos a publicar
  command = "npm install && npx ng build --configuration production"  # Comando de build

[build.environment]
  NODE_VERSION = "18"                                  # Versión de Node.js para el build

# Configuración de redirecciones para SPA (Single Page Application)
[[redirects]]
  from = "/*"                                          # Todas las rutas
  to = "/index.html"                                   # Redirigir al index.html
  status = 200                                         # Status code 200 (OK)

# Configuración para desarrollo local con Netlify CLI
[dev]
  command = "ng serve"                                 # Comando para desarrollo
  port = 4200                                          # Puerto de desarrollo
  publish = "dist/frontend/browser"                    # Directorio de publicación 